### ISSUE TITLE
Read an Item from a Wishlist 

### ISSUE THREAD

**Issue by sathvikabm** [CSCI-GA-2820-SU23-001/wishlists#16]
**As a** user
**I need** to be able to lookup a particular wishlisted item
**So that** I can make required changes to it
   
 ### Details and Assumptions
 * The wishlist-item mappings are stored in the database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that the service is available
 When the user attempts to lookup a particular item
 Then one of two things should happen:
 1.  If no wishlist contains the requested item, 404_NOT_FOUND 
 2.  Else, it returns the record which matches the id

```

**Comment by sohailhodarkar** [comment]
Is this similar to #13?

**Comment by sathvikabm** [comment]
No, #13, #14 is to display everything thats there 
This is a "search" for a particular product and see which wishlist it belongs to
Or a particular wishlist
