### ISSUE TITLE
Updating a Wishlisted Item

### ISSUE THREAD

**Issue by ZhiruoLi** [CSCI-GA-2820-SU23-001/wishlists#22]
**As a** product owner
**I need** to be able to update the details of a product (name, price, etc...)
**So that** the most-recent information can be viewed when the item is viewed through the wishlist
   
 ### Details and Assumptions
 * An update to the details of a product, should be triggered by the products team
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that the service is available.
 When the products team attempt to update the details of a product
 Then one of two things should happen:
 1.  If the item does not belong to any of the wishlists, then the update must fail (404_NOT_FOUND)
 2.  Else, the item details must be updated in every wishlist thereby indicating success (200_OK)

```

**Comment by sohailhodarkar** [comment]
Closed with #30
