### ISSUE TITLE
Creating a Relational Database

### ISSUE THREAD

**Issue by sathvikabm** [CSCI-GA-2820-SU23-001/wishlists#6]
**As a** developer
**I need** to be able to store user-wishlist and wishlist-product mappings
**So that** I can access them as part of operations

 ### Details and Assumptions
 * The database model should consist of two tables: one for user-wishlist mappings and the other for wishlist-product mappings
 * Columns for user-wishlist table: user-id, wishlist-id, wishlist-name, wishlist-capacity
 * Columns for wishlist-product table: wishlist-id, product-id, product-name, product-price
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that the service is available
 When information is to be retrieved/added to the storage
 Then the required operation must be performed on the database

```

**Comment by sohailhodarkar** [comment]
Closed with #23
