### ISSUE TITLE
Deploy to the Cloud: Create a Kubernetes cluster

### ISSUE THREAD

**Issue by ZhiruoLi** [CSCI-GA-2820-SU23-001/wishlists#66]
**As an** Admin
**I need** to be able to have a cluster 
**So that** on that particular cluster expected functionalities are performed 

 ### Details and Assumptions
 cluster and namespace required to run pods
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the cluster exists
 When deployed on cloud
 Then it should be able to talk to pods and talk to the required containers
```

**Comment by MingChieh** [comment]
We can use the one I created for the lab

**Comment by sohailhodarkar** [comment]
Yes, my bad. We shall go ahead with the one you created for the lab
